kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: go
  name: go-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
        - name: go
          image: <YOUR_DOCKERHUB_ACCOUNT>/web-go:1.0
          ports:
            - name: web
              containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: go
  namespace: default
spec:
  selector:
    app: go
  ports:
    - protocol: TCP
      port: 8080
      name: web
      targetPort: 8080
  type: NodePort
