kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: quarkus-jvm
  name: quarkus-jvm-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-jvm
  template:
    metadata:
      labels:
        app: quarkus-jvm
    spec:
      containers:
        - name: quarkus-jvm
          image: <YOUR_DOCKERHUB_ACCOUNT>/web-quarkus-jvm:1.0
          ports:
            - name: web
              containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: quarkus-jvm
  namespace: default
spec:
  selector:
    app: quarkus-jvm
  ports:
    - protocol: TCP
      port: 8080
      name: web
      targetPort: 8080
  type: NodePort
