kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: quarkus-native
  name: quarkus-native-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-native
  template:
    metadata:
      labels:
        app: quarkus-native
    spec:
      containers:
        - name: quarkus-native
          image: <YOUR_DOCKERHUB_ACCOUNT>/web-quarkus-native:1.0
          ports:
            - name: web
              containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: quarkus-native
  namespace: default
spec:
  selector:
    app: quarkus-native
  ports:
    - protocol: TCP
      port: 8080
      name: web
      targetPort: 8080
  type: NodePort
